// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
    "github.com/gogf/gf/os/gtime"
)


// TcPost is the golang structure for table tc_post.
type TcPost struct {
    Id          int         `orm:"id,primary"   json:"id"`          //                                   
    Uid         int         `orm:"uid"          json:"uid"`         //                                   
    Content     string      `orm:"content"      json:"content"`     //                                   
    CreateTime  *gtime.Time `orm:"create_time"  json:"createTime"`  //                                   
    ViewSum     int         `orm:"view_sum"     json:"viewSum"`     // 查看次数                          
    IsAnonymous int         `orm:"is_anonymous" json:"isAnonymous"` // 是否匿名，默认：1-开放，2-匿名    
    LoveSum     int         `orm:"love_sum"     json:"loveSum"`     // 点赞次数                          
    IsSquare    int         `orm:"is_square"    json:"isSquare"`    // 是否投放到广场，默认：1-是，2-否  
}


// TcPostLove is the golang structure for table tc_post_love.
type TcPostLove struct {
    Id         int         `orm:"id,primary"  json:"id"`         //   
    PostId     int         `orm:"post_id"     json:"postId"`     //   
    UserId     int         `orm:"user_id"     json:"userId"`     //   
    CreateTime *gtime.Time `orm:"create_time" json:"createTime"` //   
}


// TcUser is the golang structure for table tc_user.
type TcUser struct {
    Id            int         `orm:"id,primary"      json:"id"`            //                                   
    Phone         string      `orm:"phone"           json:"phone"`         //                                   
    AvatarUrl     string      `orm:"avatar_url"      json:"avatarUrl"`     //                                   
    Nickname      string      `orm:"nickname"        json:"nickname"`      //                                   
    Openid        string      `orm:"openid,unique"   json:"openid"`        //                                   
    Unionid       string      `orm:"unionid"         json:"unionid"`       //                                   
    Gender        int         `orm:"gender"          json:"gender"`        //                                   
    CreateTime    *gtime.Time `orm:"create_time"     json:"createTime"`    //                                   
    SessionKey    string      `orm:"session_key"     json:"sessionKey"`    //                                   
    LastLoginTime *gtime.Time `orm:"last_login_time" json:"lastLoginTime"` //                                   
    PostSum       int         `orm:"post_sum"        json:"postSum"`       //                                   
    IsAnonymous   int         `orm:"is_anonymous"    json:"isAnonymous"`   // 是否匿名，默认：1-开放，2-匿名    
    IsSquare      int         `orm:"is_square"       json:"isSquare"`      // 是否投放到广场，默认：1-是，2-否  
}