// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go_api/app/dao/internal"
)

// tcPostDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type tcPostDao struct {
	*internal.TcPostDao
}

var (
	// TcPost is globally public accessible object for table tc_post operations.
	TcPost tcPostDao
)

func init() {
	TcPost = tcPostDao{
		internal.NewTcPostDao(),
	}
}

// Fill with you ideas below.
