// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// TcPostLoveDao is the manager for logic model data accessing and custom defined data operations functions management.
type TcPostLoveDao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C       tcPostLoveColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.	
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the underlying table name of the DAO.
}

// TcPostLoveColumns defines and stores column names for table tc_post_love.
type tcPostLoveColumns struct {
	Id          string //   
    PostId      string //   
    UserId      string //   
    CreateTime  string //
}

// NewTcPostLoveDao creates and returns a new DAO object for table data access.
func NewTcPostLoveDao() *TcPostLoveDao {
    columns := tcPostLoveColumns{
		Id:         "id",           
            PostId:     "post_id",      
            UserId:     "user_id",      
            CreateTime: "create_time",
	}
	return &TcPostLoveDao{
		C: 	   columns,
		M:     g.DB("default").Model("tc_post_love").Safe(),
		DB:    g.DB("default"),
		Table: "tc_post_love",
	}
}