// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// TcPostDao is the manager for logic model data accessing and custom defined data operations functions management.
type TcPostDao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C       tcPostColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.	
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the underlying table name of the DAO.
}

// TcPostColumns defines and stores column names for table tc_post.
type tcPostColumns struct {
	Id           string //                                   
    Uid          string //                                   
    Content      string //                                   
    CreateTime   string //                                   
    ViewSum      string // 查看次数                          
    IsAnonymous  string // 是否匿名，默认：1-开放，2-匿名    
    LoveSum      string // 点赞次数                          
    IsSquare     string // 是否投放到广场，默认：1-是，2-否
}

// NewTcPostDao creates and returns a new DAO object for table data access.
func NewTcPostDao() *TcPostDao {
    columns := tcPostColumns{
		Id:          "id",            
            Uid:         "uid",           
            Content:     "content",       
            CreateTime:  "create_time",   
            ViewSum:     "view_sum",      
            IsAnonymous: "is_anonymous",  
            LoveSum:     "love_sum",      
            IsSquare:    "is_square",
	}
	return &TcPostDao{
		C: 	   columns,
		M:     g.DB("default").Model("tc_post").Safe(),
		DB:    g.DB("default"),
		Table: "tc_post",
	}
}